defaults: &defaults
  working_directory: ~/zssn
  docker:
    - image: circleci/node:8.9.3
    - image: mongo:3.4.1

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: npm-install
          command: npm install
      - run:
          name: npm-test
          command: npm test